---
title: "R Notebook"
output: html_notebook
---

```{r}
source("../function.R")
```



```{r, fig.width = 20, fig.height = 10}
df <- data.frame(pattern = c('regular', 'random', 'aggregation 1', 'aggregation 2', 'aggregation 3'), index = c(QNN(df_re, xr, yr, floor(1000/19), floor(500/9))$ar, 
                                                                                                                QNN(df_ra, xr, yr, r)$ar,
                                                                                                                QNN(df_ag1, xr, yr, r)$ar,
                                                                                                                QNN(df_ag2, xr, yr, r)$ar,
                                                                                                                QNN(df_ag3, xr, yr, r)$ar))

#x11(20, 10)
p<-ggplot(data=df, aes(x=factor(pattern, levels = unique(pattern)), y=index)) +
  geom_bar(stat="identity", width=.5)+
  xlab('')+
  ylab('')+
  geom_text(aes(label = round(index, 2)), vjust = -0.35, colour = "red", size=9)+
  theme(plot.title = element_text(hjust = 0.5, size = 30), axis.text.x=element_text(size=30), axis.text.y=element_text(size=30))
p
```

